@WebAPI_HostAddress = http://localhost:5260

GET {{WebAPI_HostAddress}}/Channel
Accept: application/json

###

GET {{WebAPI_HostAddress}}/Channel/1
Accept: application/json

###

POST {{WebAPI_HostAddress}}/Channel
Content-Type: application/json

{
  "name": "Announcements",
  "description": "Company announcements"
}

###

PUT {{WebAPI_HostAddress}}/Channel/1
Content-Type: application/json

{
  "name": "General chat",
  "description": "Updated general company discussion"
}

###

DELETE {{WebAPI_HostAddress}}/Channel/2

###
